run:
  tests: false
  concurrency: 4

linters:
  enable:
    - gofmt
    - govet
    - gocyclo
    - ineffassign
    - typecheck
    - revive
    - unconvert
    - goconst
    - gocyclo
    - staticcheck
    - unused
    - gosimple
    - dupl
    - gofmt
    - lll
    - megacheck
    - gocritic