name: Go tests

on: [ pull_request ]

jobs:
  build:

    strategy:
      matrix:
        go-version: [ '1.16.x', '1.17.x', '1.18.x', '1.19.x' ]
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }} on ${{ matrix.os }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Run tests
        run: go test -json -race ./... > TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.os }}-${{ matrix.go-version }}
          path: TestResults-${{ matrix.os }}-${{ matrix.go-version }}.json
